//This file is auto-generated by 'github.com/jaihind213/auto_proto_registry_loader' . please dont modify the file!" 
package pocket_registry

import _ "github.com/jaihind213/auto_proto_registry_loader/go_bindings/foo"
