package go_bindings

// This package houses the golang code generated by protobuff binary (protoc)
// It also houses a auto-generated file to load the protobuf registry with the types.

// example: protoc --proto_path=. --go_out=../go_bindings/ ./foo/**/*
